language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .[tests]
# command to run tests
script:
  - pytest --cov=ething
after_success:
  - coveralls
